on:
  push:
    tags:
      - '*staging*'

name: Deploy on staging tag
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: '14.7.0'
          registry-url: https://npm.pkg.github.com
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Get the version
        id: get_version
        # Available at ${{ steps.get_version.outputs.VERSION }}
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - run: echo ${{ steps.get_version.outputs.VERSION }}
