on:
  push:
    branches:
      - main

name: Release on pre
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    if: ${{ github.event.head_commit.message != 'release**pre**' }}
    steps:
      - run: echo ${{ github.event.head_commit.message != 'release**pre**' }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: '14.7.0'
          registry-url: https://npm.pkg.github.com
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Start release
        run: |
          git status
          git config user.name 'Davi Kawasaki'
          git config user.email 'davishinjik@gmail.com'
          MASTER=main ./rel version pre
