on: 
  workflow_dispatch:
    inputs:
      hot_fix_branch:
        description: 'Whether or not should checkout and deploy a hot fix from a specific staging branch'
        required: false
        default: ''

name: Manual release for staging
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.actor == 'davikawasaki'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
        if: ${{ github.event.inputs.hot_fix_branch }} == ''
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
          ref: ${{ github.event.inputs.hot_fix_branch }}
        if: ${{ github.event.inputs.hot_fix_branch }} != ''
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: '14.7.0'
          registry-url: https://npm.pkg.github.com
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Start release
        run: |
          git status
          git config user.name 'Davi Kawasaki'
          git config user.email 'davishinjik@gmail.com'
          RC=staging MASTER=main ./rel version rc
